"""Konfigurasi Predict Today."""

MIN_TRANSACTIONS_FOR_PREDICTION = 2
MIN_SERVICE_USAGE = 1

MIN_CYCLE_DAYS = 1
MAX_CYCLE_DAYS = 90

MAX_CARRY_OVER = 3
MAX_RELATIVE_DEVIATION = 0.35

MATCH_DELTA_MIN = -1
MATCH_DELTA_MAX = 0
